default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432


development:
  <<: *default
  database: pdf_generator_development
  username: postgres
  password: password
  host: localhost